wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1657913151
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.8.13
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epoch:
  desc: null
  value: 10
layer_1:
  desc: null
  value: 13
layer_2:
  desc: null
  value: 12
learn_rate:
  desc: null
  value: 0.02218
